apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "loadbalancer"
spec:
  type: LoadBalancer
  loadBalancerIP: 197.6.0.206
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: ubuntu
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
---