apiVersion: v1
kind: Service
metadata:
  name: inspectorgadget
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "loadbalancer"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.76.0.36
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: inspectorgadget
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspector-gadget
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inspectorgadget
      tier: front-end
  template:
    metadata:
      labels:
        app: inspectorgadget
        tier: front-end
    spec:
      containers:
      - name: inspectorgadget
        image: jelledruyts/inspectorgadget
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          name: http
        env:
        - name: tier
          value: "Front End"
        - name: InfoMessage
          value: "You're on the Front End tier"
        - name: BackgroundColor
          value: "#fbfbfb"
---