apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: inspectorgadget-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
  - http:
      paths:
      - path: /inspectorgadget/
        backend:
          serviceName: inspectorgadget-service
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inspectorgadget-service
spec:
  selector:
    app: inspectorgadget
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspector-gadget
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inspectorgadget
      tier: front-end
  template:
    metadata:
      labels:
        app: inspectorgadget
        tier: front-end
    spec:
      containers:
      - name: inspectorgadget
        image: jelledruyts/inspectorgadget
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          name: http
        env:
        - name: tier
          value: "Front End"
        - name: InfoMessage
          value: "You're on the Front End tier"
        - name: BackgroundColor
          value: "#fbfbfb"
---